In [1]:
# import dependencies
import pandas as pd
import gmaps
import gmaps.datasets
import requests
from config import g_key

In [2]:
# read the csv from part 1
city_data_df = pd.read_csv('weather_data/cities.csv')

In [3]:
new_column_order = ['City_ID', 'City', 'Country', 'Date', 'Lat', 'Lng', 'Max Temp', 'Humidity', 'Cloudiness', 'Wind Speed']
city_data_df = city_data_df[new_column_order]

In [4]:
city_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City_ID     566 non-null    int64
 1   City        566 non-null    object
 2   Country     562 non-null    object
 3   Date        566 non-null    object
 4   Lat         566 non-null    float64
 5   Lng         566 non-null    float64
 6   Max Temp    566 non-null    float64
 7   Humidity    566 non-null    int64
 8   Cloudiness  566 non-null    int64
 9   Wind Speed  566 non-null    float64
dtypes: float64(4), int64(3), object(3)
memory usage: 44.3+ KB

In [5]:
# configure gmaps to use your Google API key
gmaps.configure(api_key=g_key)

In [6]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [7]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
#show the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig1 = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig1 = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig1 = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [12]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
4,4,Panique,PH,2022-04-03 16:00:45,12.4797,122.0153,80.28,75,47,18.61
8,8,Butaritari,KI,2022-04-03 16:00:46,3.0707,172.7902,81.18,72,59,14.32
10,10,Rikitea,PF,2022-04-03 16:00:47,-23.1203,-134.9692,76.10,64,44,9.04
13,13,Lorengau,PG,2022-04-03 16:00:48,-2.0226,147.2712,79.70,80,100,1.86
15,15,Puerto Ayora,EC,2022-04-03 16:00:48,-0.7393,-90.3518,81.03,78,89,10.60
17,17,Poso,ID,2022-04-03 16:00:49,-1.3959,120.7524,78.48,83,100,4.63
35,35,Barreirinhas,BR,2022-04-03 16:00:38,-2.7469,-42.8264,88.97,56,67,7.61
45,45,East London,ZA,2022-04-03 15:59:21,-33.0153,27.9116,76.14,78,0,14.97
48,48,Bengkulu,ID,2022-04-03 16:01:59,-3.8004,102.2655,77.23,81,50,4.68
53,53,Grand Gaube,MU,2022-04-03 16:02:00,-20.0064,57.6608,79.38,79,77,5.01

In [13]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
4        Panique      PH     80.28  12.4797  122.0153
8     Butaritari      KI     81.18   3.0707  172.7902
10       Rikitea      PF     76.10 -23.1203 -134.9692
13      Lorengau      PG     79.70  -2.0226  147.2712
15  Puerto Ayora      EC     81.03  -0.7393  -90.3518
17          Poso      ID     78.48  -1.3959  120.7524
35  Barreirinhas      BR     88.97  -2.7469  -42.8264
45   East London      ZA     76.14 -33.0153   27.9116
48      Bengkulu      ID     77.23  -3.8004  102.2655
53   Grand Gaube      MU     79.38 -20.0064   57.6608

In [14]:
# set the parameters to search for a hotel
params = {
    'radius': 5000,
    'type': 'lodging',
    'key': g_key
}

In [17]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print(f"Hotel not found in {hotel_df.loc[index, 'City']} skipping.")

Hotel not found in Poum skipping.
Hotel not found in Orange Walk skipping.
Hotel not found in Maraa skipping.
Hotel not found in Bonfim skipping.
Hotel not found in Mitu skipping.
Hotel not found in Jurado skipping.
Hotel not found in Tchibanga skipping.
Hotel not found in Balaipungut skipping.
Hotel not found in Nalut skipping.
Hotel not found in Tucuma skipping.
Hotel not found in Imelda skipping.
Hotel not found in Marzuq skipping.
Hotel not found in Merauke skipping.

In [18]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
4,Panique,PH,80.28,12.4797,122.0153,Panique Cove Resort
8,Butaritari,KI,81.18,3.0707,172.7902,Isles Sunset Lodge
10,Rikitea,PF,76.10,-23.1203,-134.9692,People ThankYou
13,Lorengau,PG,79.70,-2.0226,147.2712,Lorengau Harbourside Hotel
15,Puerto Ayora,EC,81.03,-0.7393,-90.3518,Finch Bay Galapagos Hotel
...,...,...,...,...,...,...
555,Puri,IN,81.12,19.8000,85.8500,OYO 1577 Hotel Shree Hari Grand
556,Yokadouma,CM,82.08,3.5167,15.0500,Hôtel De Ville De Yokadouma
561,Merauke,ID,78.17,-8.4667,140.3333,
562,Chauk,MM,84.51,20.8833,94.8167,Bo Khin Guest House
563,Inhambane,MZ,78.66,-23.8650,35.3833,Oceano

In [21]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [22]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))